Repository dd-ix/nix-config, pull requests merged in 2023-09, with the labels that each got.

#15 Add Basic Auth for Website
  flake.lock
  modules/management/website.nix
Labels: enhancement, auth

#14 Listmonk
  flake.lock
  flake.nix
  modules/management/default.nix
  modules/management/listmonk.nix
  modules/management/website.nix
  secrets/management/secrets.yaml
Labels: enhancement

#21 Bookstack
  modules/management/bookstack.nix
  modules/management/default.nix
  secrets/management/secrets.yaml
Labels: enhancement, auth

#17 bind9: add new service
  modules/dd-ix/base.nix
  modules/management/bind9.nix
  modules/management/default.nix
Labels: enhancement, services
