Repository dd-ix/nix-config, pull requests merged in 2024-01, with the labels that each got.

#2 migrating to networkd
  hosts/mno001/configuration.nix
  hosts/mno001/initrd_network.nix
  hosts/mno001/network.nix
  modules/management/website.nix
Labels: enhancement, network

#44 Added zone dd-ix.net
  hosts/mno001/network.nix
  modules/management/bind9.nix
  resources/0.b.0.8.0.0.7.7.1.0.a.2.ip6.arpa.zone
  resources/dd-ix.net.zone
Labels: enhancement, management

#52 bind9: add RRs for sw-c2-svc1
  resources/0.b.0.8.0.0.7.7.1.0.a.2.ip6.arpa.zone
  resources/dd-ix.net.zone
Labels: enhancement

#53 Update bind9 zones
  resources/0.b.0.8.0.0.7.7.1.0.a.2.ip6.arpa.zone
Labels: bug, enhancement

#55 bind9: add reverse zone for IPv4 PA prefix
  modules/management/bind.nix
  resources/176.245.111.212.in-addr.arpa.zone
Labels: enhancement

#56 bind9: add ptr for legacy nat address
  resources/176.245.111.212.in-addr.arpa.zone
Labels: enhancement

#58 mta-mno001: add mail relay instance
  flake.nix
  hosts/mta-mno001/configuration.nix
  hosts/mta-mno001/default.nix
  modules/management/postfix.nix
  resources/0.b.0.8.0.0.7.7.1.0.a.2.ip6.arpa.zone
  resources/176.245.111.212.in-addr.arpa.zone
  resources/dd-ix.net.zone
Labels: enhancement, help wanted

#61 listmonk: add bounce mailbox (WIP)
  modules/management/listmonk.nix
  secrets/management/secrets.yaml
Labels: enhancement
